.phony all:
all: f1 f2 f3

f1: diskinfo.c
	gcc -Wall diskinfo.c -o diskinfo
	
f2: disklist.c
	gcc -Wall disklist.c -o disklist
	
f3: diskget.c
	gcc -Wall diskget.c -o diskget

f4: diskput.c
	gcc -Wall diskput.c -o diskput
	
.PHONY clean:
clean:
	-rm -rf *.o *.exe
